### ISSUE TITLE
mod launcher crash with more craftables

### ISSUE THREAD

**Issue by Arathok** [ausimus/wurmunlimited-morecraftables#1]
Hello, im  a fresh modlauncher user and everything seems to work except it throws an exception when I installed your modifcation:

SEVERE org.gotti.wurmunlimited.serverlauncher.DelegatedLauncher: java.lang.ClassNotFoundException: org.ausimus.wurmunlimited.mods.morecraftables.Initiator
org.gotti.wurmunlimited.modloader.classhooks.HookException: java.lang.ClassNotFoundException: org.ausimus.wurmunlimited.mods.morecraftables.Initiator
	at org.gotti.wurmunlimited.modloader.ModInstanceBuilder.createModInstance(ModInstanceBuilder.java:74)
	at org.gotti.wurmunlimited.modloader.ModLoaderShared.lambda$loadModsFromModDir$1(ModLoaderShared.java:141)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.gotti.wurmunlimited.modloader.ModLoaderShared.loadModsFromModDir(ModLoaderShared.java:143)
	at org.gotti.wurmunlimited.serverlauncher.DelegatedLauncher.main(DelegatedLauncher.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javassist.Loader.run(Loader.java:286)
	at org.gotti.wurmunlimited.serverlauncher.ServerLauncher.main(ServerLauncher.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at PatchedLauncher.main(PatchedLauncher.java:20)
Caused by: java.lang.ClassNotFoundException: org.ausimus.wurmunlimited.mods.morecraftables.Initiator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at javassist.Loader.delegateToParent(Loader.java:431)
	at org.gotti.wurmunlimited.modloader.classhooks.HookManager$1.delegateToParent(HookManager.java:174)
	at javassist.Loader.loadClass(Loader.java:311)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.gotti.wurmunlimited.modloader.ModInstanceBuilder.createModInstance(ModInstanceBuilder.java:72)
	... 21 more

Im on ubuntu 18.04 and i have java 8 installed...
Im by no means a pro so any help would be greatly appreciated, since i really like to decorate my house!

Have a nice day!

**Comment by Arathok** [comment]
Can be closed, somehow i only installed the hotfix
